# Generated by Django 5.0 on 2023-12-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='item_images/')),
                ('image2', models.ImageField(upload_to='item_images/')),
                ('time', models.DateTimeField()),
                ('koef1', models.FloatField()),
                ('koef2', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
